spring.application.name=testmid
#URL del contexto
server.servlet.context-path=/testmid

version.aplicativo=0.0.1

spring.datasource.url=jdbc:postgresql://localhost:5432/db_testmid
spring.datasource.username=postgres
#spring.datasource.password=123456789 
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect